In [1]:
# !pip install pip install scikit-learn

In [2]:
import os
os.getcwd()

'C:\\Users\\user'

In [6]:
import pandas as pd

In [12]:
pd.read_excel("BTC.xlsx").head()

Date        Open        High         Low       Close   Adj Close  \
0 2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1 2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2 2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
3 2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
4 2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0  
3  36863600.0  
4  26580100.0

In [14]:
BTC = pd.read_excel("BTC.xlsx")

In [15]:
BTC.head(3)

Date        Open        High         Low       Close   Adj Close  \
0 2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1 2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2 2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0

In [16]:
BTC.shape

(2437, 7)

In [17]:
import pandas as pd
import numpy as np

In [19]:
inputs = {
    'open': np.random.random(5),
    'high': np.random.random(5),
    'low': np.random.random(5),
    'close': np.random.random(5),
    'volume': np.random.random(5)
}

In [20]:
print(type(inputs))
inputs

<class 'dict'>


{'open': array([0.2767522 , 0.15421509, 0.43586399, 0.19054569, 0.02748801]),
 'high': array([0.53019379, 0.12972741, 0.27256405, 0.36350825, 0.32092406]),
 'low': array([0.55312213, 0.08528313, 0.76218878, 0.69350819, 0.72559726]),
 'close': array([0.89996965, 0.24993693, 0.3815004 , 0.04932822, 0.33500984]),
 'volume': array([0.02709085, 0.41755255, 0.16782031, 0.87313474, 0.62237972])}

In [21]:
print(type(inputs["open"]))
inputs["open"]

<class 'numpy.ndarray'>


array([0.2767522 , 0.15421509, 0.43586399, 0.19054569, 0.02748801])

In [22]:
print(type(np.random.random(5)))
np.random.random(5)

<class 'numpy.ndarray'>


array([0.52832255, 0.63263646, 0.76192097, 0.11888447, 0.72439672])

In [23]:
BTC.head()

Date        Open        High         Low       Close   Adj Close  \
0 2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1 2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2 2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
3 2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
4 2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0  
3  36863600.0  
4  26580100.0

In [24]:
print(type(BTC["Open"]))
BTC["Open"]

<class 'pandas.core.series.Series'>


0         465.864014
1         456.859985
2         424.102997
3         394.673004
4         408.084991
            ...     
2432    49855.496094
2433    46716.636719
2434    46415.898438
2435    43488.058594
2436    42673.000000
Name: Open, Length: 2437, dtype: float64

In [25]:
# note that all ndarrays must be the same length!
inputs = {
    'open': BTC["Open"],
    'high': BTC["High"],
    'low':  BTC["Low"],
    'close':  BTC["Adj Close"],
    'volume': BTC["Volume"]
}

In [26]:
from talib.abstract import *

In [27]:
inputs["open"]

0         465.864014
1         456.859985
2         424.102997
3         394.673004
4         408.084991
            ...     
2432    49855.496094
2433    46716.636719
2434    46415.898438
2435    43488.058594
2436    42673.000000
Name: Open, Length: 2437, dtype: float64

In [28]:
pd.isna(BTC)

Date   Open   High    Low  Close  Adj Close  Volume
0     False  False  False  False  False      False   False
1     False  False  False  False  False      False   False
2     False  False  False  False  False      False   False
3     False  False  False  False  False      False   False
4     False  False  False  False  False      False   False
...     ...    ...    ...    ...    ...        ...     ...
2432  False  False  False  False  False      False   False
2433  False  False  False  False  False      False   False
2434  False  False  False  False  False      False   False
2435  False  False  False  False  False      False   False
2436  False  False  False  False  False      False   False

[2437 rows x 7 columns]

In [29]:
BTC.isnull().values.any()

True

In [30]:
pd.DataFrame(BTC).dropna()

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2432 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2433 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2434 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2435 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2436 2021-05-19  42673.000000  43546.117188  38787.902344  39458.335938   

         Adj Close        Volume  
0       457.334015  2.105680e+07  
1       424.440002  3.448320e+07  
2       394.795990  3.791970e+07  
3       408.903992  3.686360e+07  
4       398.821014  2.658010e+07  
...            ...           ...  
2432  46760.187500  5.916105e+10  
2433  46456.058594  6.404787e+10  
2434  43537.511719  7.490364e+10  
2435  42909.402344  5.618737e+10  
2436  39458.335938  6.763069e+10  

[2433 rows x 7 columns]

In [31]:
modify_BTC = pd.DataFrame(BTC).dropna()

In [32]:
modify_BTC = modify_BTC.reset_index().drop(columns=['index'])

In [33]:
modify_BTC

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432 2021-05-19  42673.000000  43546.117188  38787.902344  39458.335938   

         Adj Close        Volume  
0       457.334015  2.105680e+07  
1       424.440002  3.448320e+07  
2       394.795990  3.791970e+07  
3       408.903992  3.686360e+07  
4       398.821014  2.658010e+07  
...            ...           ...  
2428  46760.187500  5.916105e+10  
2429  46456.058594  6.404787e+10  
2430  43537.511719  7.490364e+10  
2431  42909.402344  5.618737e+10  
2432  39458.335938  6.763069e+10  

[2433 rows x 7 columns]

In [34]:
# note that all ndarrays must be the same length!
inputs = {
    'open': modify_BTC["Open"],
    'high': modify_BTC["High"],
    'low':  modify_BTC["Low"],
    'close':  modify_BTC["Adj Close"],
    'volume': modify_BTC["Volume"]
}

In [35]:
pd.DataFrame(SMA(inputs, timeperiod = 5, price='open')).head(10)

0
0         NaN
1         NaN
2         NaN
3         NaN
4  429.916998
5  416.564197
6  405.610602
7  407.940204
8  413.636804
9  414.305603

In [36]:
open_5ma   = SMA(inputs, timeperiod = 5, price='open')
close_5ma  = SMA(inputs, timeperiod = 5, price='close')
close_10ma = SMA(inputs, timeperiod = 10, price='close')
close_20ma = SMA(inputs, timeperiod = 20, price='close')

In [37]:
modify_BTC.head(3)

Date        Open        High         Low       Close   Adj Close  \
0 2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1 2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2 2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   

       Volume  
0  21056800.0  
1  34483200.0  
2  37919700.0

In [38]:
open_5ma

array([          nan,           nan,           nan, ..., 48481.2890628,
       47231.8140628, 45829.817969 ])

In [39]:
modify_BTC

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432 2021-05-19  42673.000000  43546.117188  38787.902344  39458.335938   

         Adj Close        Volume  
0       457.334015  2.105680e+07  
1       424.440002  3.448320e+07  
2       394.795990  3.791970e+07  
3       408.903992  3.686360e+07  
4       398.821014  2.658010e+07  
...            ...           ...  
2428  46760.187500  5.916105e+10  
2429  46456.058594  6.404787e+10  
2430  43537.511719  7.490364e+10  
2431  42909.402344  5.618737e+10  
2432  39458.335938  6.763069e+10  

[2433 rows x 7 columns]

In [40]:
modify_BTC["y"] = None

In [41]:
modify_BTC

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432 2021-05-19  42673.000000  43546.117188  38787.902344  39458.335938   

         Adj Close        Volume     y  
0       457.334015  2.105680e+07  None  
1       424.440002  3.448320e+07  None  
2       394.795990  3.791970e+07  None  
3       408.903992  3.686360e+07  None  
4       398.821014  2.658010e+07  None  
...            ...           ...   ...  
2428  46760.187500  5.916105e+10  None  
2429  46456.058594  6.404787e+10  None  
2430  43537.511719  7.490364e+10  None  
2431  42909.402344  5.618737e+10  None  
2432  39458.335938  6.763069e+10  None  

[2433 rows x 8 columns]

In [42]:
import math

In [43]:
math.log(120, 10)

2.0791812460476247

In [44]:
modify_BTC.iloc[1, 5]


424.440002

In [45]:
math.log( modify_BTC.iloc[1, 5]/modify_BTC.iloc[0, 5] , 10)

-0.03241719606846411

In [46]:
modify_BTC.shape[0]

2433

In [48]:
for i in range(0, modify_BTC.shape[0]-1):
    modify_BTC.iloc[i, -1] = math.log( modify_BTC.iloc[i+1, 5]/modify_BTC.iloc[i, 5] , 10)

In [49]:
modify_BTC

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   
2432 2021-05-19  42673.000000  43546.117188  38787.902344  39458.335938   

         Adj Close        Volume         y  
0       457.334015  2.105680e+07 -0.032417  
1       424.440002  3.448320e+07 -0.031444  
2       394.795990  3.791970e+07  0.015249  
3       408.903992  3.686360e+07 -0.010843  
4       398.821014  2.658010e+07  0.003612  
...            ...           ...       ...  
2428  46760.187500  5.916105e+10 -0.002834  
2429  46456.058594  6.404787e+10 -0.028179  
2430  43537.511719  7.490364e+10 -0.006311  
2431  42909.402344  5.618737e+10 -0.036414  
2432  39458.335938  6.763069e+10      None  

[2433 rows x 8 columns]

In [50]:
modify_BTC.dropna()

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2427 2021-05-14  49682.980469  51438.117188  48868.578125  49880.535156   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   

         Adj Close        Volume         y  
0       457.334015  2.105680e+07 -0.032417  
1       424.440002  3.448320e+07 -0.031444  
2       394.795990  3.791970e+07  0.015249  
3       408.903992  3.686360e+07 -0.010843  
4       398.821014  2.658010e+07  0.003612  
...            ...           ...       ...  
2427  49880.535156  5.573750e+10 -0.028055  
2428  46760.187500  5.916105e+10 -0.002834  
2429  46456.058594  6.404787e+10 -0.028179  
2430  43537.511719  7.490364e+10 -0.006311  
2431  42909.402344  5.618737e+10 -0.036414  

[2432 rows x 8 columns]

In [51]:
modify_BTC = modify_BTC.dropna()

In [52]:
modify_BTC.head()

Date        Open        High         Low       Close   Adj Close  \
0 2014-09-17  465.864014  468.174011  452.421997  457.334015  457.334015   
1 2014-09-18  456.859985  456.859985  413.104004  424.440002  424.440002   
2 2014-09-19  424.102997  427.834991  384.532013  394.795990  394.795990   
3 2014-09-20  394.673004  423.295990  389.882996  408.903992  408.903992   
4 2014-09-21  408.084991  412.425995  393.181000  398.821014  398.821014   

       Volume         y  
0  21056800.0 -0.032417  
1  34483200.0 -0.031444  
2  37919700.0  0.015249  
3  36863600.0 -0.010843  
4  26580100.0  0.003612

In [53]:
modify_BTC.tail()

Date          Open          High           Low         Close  \
2427 2021-05-14  49682.980469  51438.117188  48868.578125  49880.535156   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   

         Adj Close        Volume         y  
2427  49880.535156  5.573750e+10 -0.028055  
2428  46760.187500  5.916105e+10 -0.002834  
2429  46456.058594  6.404787e+10 -0.028179  
2430  43537.511719  7.490364e+10 -0.006311  
2431  42909.402344  5.618737e+10 -0.036414

In [54]:
modify_BTC

Date          Open          High           Low         Close  \
0    2014-09-17    465.864014    468.174011    452.421997    457.334015   
1    2014-09-18    456.859985    456.859985    413.104004    424.440002   
2    2014-09-19    424.102997    427.834991    384.532013    394.795990   
3    2014-09-20    394.673004    423.295990    389.882996    408.903992   
4    2014-09-21    408.084991    412.425995    393.181000    398.821014   
...         ...           ...           ...           ...           ...   
2427 2021-05-14  49682.980469  51438.117188  48868.578125  49880.535156   
2428 2021-05-15  49855.496094  50639.664063  46664.140625  46760.187500   
2429 2021-05-16  46716.636719  49720.042969  43963.351563  46456.058594   
2430 2021-05-17  46415.898438  46623.558594  42207.289063  43537.511719   
2431 2021-05-18  43488.058594  45812.457031  42367.832031  42909.402344   

         Adj Close        Volume         y  
0       457.334015  2.105680e+07 -0.032417  
1       424.440002  3.448320e+07 -0.031444  
2       394.795990  3.791970e+07  0.015249  
3       408.903992  3.686360e+07 -0.010843  
4       398.821014  2.658010e+07  0.003612  
...            ...           ...       ...  
2427  49880.535156  5.573750e+10 -0.028055  
2428  46760.187500  5.916105e+10 -0.002834  
2429  46456.058594  6.404787e+10 -0.028179  
2430  43537.511719  7.490364e+10 -0.006311  
2431  42909.402344  5.618737e+10 -0.036414  

[2432 rows x 8 columns]

In [55]:
modify_BTC.iloc[:, -5:-1]

Low         Close     Adj Close        Volume
0       452.421997    457.334015    457.334015  2.105680e+07
1       413.104004    424.440002    424.440002  3.448320e+07
2       384.532013    394.795990    394.795990  3.791970e+07
3       389.882996    408.903992    408.903992  3.686360e+07
4       393.181000    398.821014    398.821014  2.658010e+07
...            ...           ...           ...           ...
2427  48868.578125  49880.535156  49880.535156  5.573750e+10
2428  46664.140625  46760.187500  46760.187500  5.916105e+10
2429  43963.351563  46456.058594  46456.058594  6.404787e+10
2430  42207.289063  43537.511719  43537.511719  7.490364e+10
2431  42367.832031  42909.402344  42909.402344  5.618737e+10

[2432 rows x 4 columns]

In [56]:
X = modify_BTC.iloc[:, -5:-1]

In [57]:
modify_BTC['y']

0      -0.032417
1      -0.031444
2       0.015249
3      -0.010843
4       0.003612
          ...   
2427   -0.028055
2428   -0.002834
2429   -0.028179
2430   -0.006311
2431   -0.036414
Name: y, Length: 2432, dtype: object

In [58]:
y = modify_BTC['y']

In [59]:
X.shape

(2432, 4)

In [60]:
y.shape

(2432,)

In [61]:
X.iloc[:1214, :]

Low         Close     Adj Close        Volume
0       452.421997    457.334015    457.334015  2.105680e+07
1       413.104004    424.440002    424.440002  3.448320e+07
2       384.532013    394.795990    394.795990  3.791970e+07
3       389.882996    408.903992    408.903992  3.686360e+07
4       393.181000    398.821014    398.821014  2.658010e+07
...            ...           ...           ...           ...
1209  14208.200195  15170.099609  15170.099609  1.841390e+10
1210  14424.000000  14595.400391  14595.400391  1.666000e+10
1211  13691.200195  14973.299805  14973.299805  1.850080e+10
1212  13105.900391  13405.799805  13405.799805  1.653410e+10
1213  13158.099609  13980.599609  13980.599609  1.206570e+10

[1214 rows x 4 columns]

In [63]:
X_train = X.iloc[:1214, :]

In [64]:
X.iloc[1214:, :]

Low         Close     Adj Close        Volume
1214  13952.400391  14360.200195  14360.200195  1.276360e+10
1215  13268.000000  13772.000000  13772.000000  1.108410e+10
1216  13641.700195  13819.799805  13819.799805  1.275080e+10
1217  10194.900391  11490.500000  11490.500000  1.885380e+10
1218   9402.290039  11188.599609  11188.599609  1.883060e+10
...            ...           ...           ...           ...
2427  48868.578125  49880.535156  49880.535156  5.573750e+10
2428  46664.140625  46760.187500  46760.187500  5.916105e+10
2429  43963.351563  46456.058594  46456.058594  6.404787e+10
2430  42207.289063  43537.511719  43537.511719  7.490364e+10
2431  42367.832031  42909.402344  42909.402344  5.618737e+10

[1218 rows x 4 columns]

In [65]:
X_test = X.iloc[1214:, :]

In [66]:
y.iloc[:1214]

0      -0.032417
1      -0.031444
2       0.015249
3      -0.010843
4       0.003612
          ...   
1209   -0.016772
1210    0.011102
1211   -0.048025
1212    0.018233
1213    0.011635
Name: y, Length: 1214, dtype: object

In [67]:
y_train = y.iloc[:1214]

In [68]:
y.iloc[1214:]

1214   -0.018163
1215    0.001505
1216   -0.080163
1217   -0.011563
1218    0.010973
          ...   
2427   -0.028055
2428   -0.002834
2429   -0.028179
2430   -0.006311
2431   -0.036414
Name: y, Length: 1218, dtype: object

In [69]:
y_test = y.iloc[1214:]

In [71]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1214, 4)
(1218, 4)
(1214,)
(1218,)


In [79]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [80]:
reg = LinearRegression().fit(X_train, y_train)

In [81]:
reg.predict(X_train)

array([ 0.00089097,  0.00087581,  0.0008369 , ..., -0.0020279 ,
       -0.00622939,  0.00285593])

In [82]:
reg.predict(X_train).size

1214

In [83]:
y_train.to_numpy()

array([-0.03241719606846411, -0.031443575080708004, 0.015248617626229791,
       ..., -0.04802479080909619, 0.01823306852573096,
       0.011634696319410408], dtype=object)

In [84]:
from sklearn.metrics import mean_squared_error

In [85]:
y_true_train = y_train.to_numpy()
y_pred_train = reg.predict(X_train)
print("regression train mse: ", round(mean_squared_error(y_true_train, y_pred_train), 10))

regression train mse:  0.0002759729


In [86]:
y_true_test = y_test.to_numpy()
y_pred_test = reg.predict(X_test)
print("regression test mse: ", round(mean_squared_error(y_true_test, y_pred_test), 10))

regression test mse:  0.0009619923


In [87]:
result = []
row = []
row.append("regression train mse: ")
row.append(round(mean_squared_error(y_true_train, y_pred_train), 10))
result.append(row)
row = []
row.append("regression test mse: ")
row.append(round(mean_squared_error(y_true_test, y_pred_test), 10))
result.append(row)
pd.DataFrame(result)

0         1
0  regression train mse:   0.000276
1   regression test mse:   0.000962

In [88]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)
reg.fit(X_train, y_train)

Lasso(alpha=0.1)

In [89]:
y_true_train = y_train.to_numpy()
y_pred_train = reg.predict(X_train)
print("lasso regression train mse: ", round(mean_squared_error(y_true_train, y_pred_train), 10))

lasso regression train mse:  0.0002766001


In [90]:

y_true_test = y_test.to_numpy()
y_pred_test = reg.predict(X_test)
print("lasso regression test mse: ", round(mean_squared_error(y_true_test, y_pred_test), 10))

lasso regression test mse:  0.000591636


In [91]:
result = []
row = []
row.append("regression train mse: ")
row.append(round(mean_squared_error(y_true_train, y_pred_train), 10))
result.append(row)
row = []
row.append("regression test mse: ")
row.append(round(mean_squared_error(y_true_test, y_pred_test), 10))
result.append(row)
pd.DataFrame(result)

0         1
0  regression train mse:   0.000277
1   regression test mse:   0.000592

In [92]:
from sklearn import tree
reg = tree.DecisionTreeRegressor()
reg = reg.fit(X_train, y_train)

In [93]:
y_true_train = y_train.to_numpy()
y_pred_train = reg.predict(X_train)
print("lasso regression train mse: ", round(mean_squared_error(y_true_train, y_pred_train), 10))
y_true_test = y_test.to_numpy()
y_pred_test = reg.predict(X_test)
print("lasso regression test mse: ", round(mean_squared_error(y_true_test, y_pred_test), 10))
result = []
row = []
row.append("regression train mse: ")
row.append(round(mean_squared_error(y_true_train, y_pred_train), 10))
result.append(row)
row = []
row.append("regression test mse: ")
row.append(round(mean_squared_error(y_true_test, y_pred_test), 10))
result.append(row)
pd.DataFrame(result)

lasso regression train mse:  0.0
lasso regression test mse:  0.0012419563


0         1
0  regression train mse:   0.000000
1   regression test mse:   0.001242